openSUSE/Mojo-IOLoop-ReadWriteProcess

- lib/Mojo/IOLoop/ReadWriteProcess/CGroup.pm
- lib/Mojo/IOLoop/ReadWriteProcess/CGroup/v1.pm
This is a fix for #4. In Mojolicious 8.23 we no longer allow `undef` values in `Mojo::File` to prevent common accidents when deleting files/directories (since there is no sensible use case where you actually want `undef` in your path).
> Fix compatibility with Mojolicious 8.23

- lib/Mojo/IOLoop/ReadWriteProcess.pm
- t/01_run.t
By default the sleep time between sending term/kill signals is 1s
meaning that previously the termination of each process took *at least*
1s which adds up in multi-process applications. There should be no need
to wait until we send out the first signal to the process to stop.
> In "stop" sleep only after sending the first signal to speedup termination

- t/01_run.t
As fb9bc63 deleted the internal timeout within the "stop()" method some
tests need to be adjusted to prevent sporadic test failures same as
already done in fb9bc63 for another test. The fix is done using the same
approach, i.e. adding a `sleep 1` to give a chance to the subprocesses
to print some output.
Verified with 10/10 successful local test runs.
> Fix sporadic test failures introduced by fb9bc63

- t/01_run.t
- t/data/process_check.sh
* t: Fix flaky test failures in 01_run.t after removing timeout in "stop()"
* t: Generalize test for 'diag' to also accept format from perl debugger
* t: Prevent line wrap in test explanation string to prevent confusion
* t: Fix incorrect english spelling in explanation string
* t: Delete duplicate test line 'pipes are correctly disabled'
> Fix flaky test failures in 01_run.t; improve tests

- .travis.yml
- cpanfile
Perl < 5.16 is no longer supported by Mojolicious
https://github.com/mojolicious/mojo/commit/52a237a813e778a998caa99e71dd8c8d5fd0cd2a
> Change minimum perl to 5.16

- lib/Mojo/IOLoop/ReadWriteProcess.pm
- t/01_run.t
- t/data/simple_fork.pl
* See particular commit messages
* See https://progress.opensuse.org/issues/67342 for the full story
* TL;DR: We want to allow ffmpeg to finalize its video.
* For that we need to prevent spamming SIGTERM signals on it without introducing long sleep times.
* We also need to be able to stop the full process group and wait for the termination of the full process group to know when ffmpeg has finalized the video.
> Improve stopping

- lib/Mojo/IOLoop/ReadWriteProcess.pm
- t/01_run.t
This saves measurably time, e.g. the os-autoinst test `t/18-qemu-options.t`
needs 28 seconds to execute on my system without this change and 11 seconds
with this change.
See https://progress.opensuse.org/issues/71110 for the motivation.
> Avoid executing "blocking stop" code when process has already terminated

- lib/Mojo/IOLoop/ReadWriteProcess/Session.pm
...as this is what the uname call gives on Fedora's 32-bit ARM
builders, at least. Not matching it ultimately leads to the
os-autoinst test suite failing on 32-bit ARM package builds.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
> Match on 'armv7l' as well as 'arm' for prctl detection

- lib/Mojo/IOLoop/ReadWriteProcess/Session.pm
If we set the child handler once, we store the old handler in our member
`handler`. But this wasn't guarded, so if someone actually creates
two processes within one `session` object, we overwrite the old handler.
> Session: Do not set SIG{CHLD} handler twice

- lib/Mojo/IOLoop/ReadWriteProcess.pm
This fix all methods which use _getlines() underneath, e.g.
read_all_stdout().
In scalar context, this function return a join() version of
`IO::Handle::getlines()`. With this fix, we avoid the extra added '\n' string.
> Fix _getlines() don't add extra '\n' string in scalar context

- lib/Mojo/IOLoop/ReadWriteProcess.pm
The `SIG{CHLD}` must be setup before we fork().
Otherwise there is a small risk of a race, that the fork already exited
before the SIG{CHLD} was set and we end up in a `$p->is_running()`
endless loop.
It is easy to reproduce, just place a `sleep 1` before this `enable()` call here https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/blob/master/lib/Mojo/IOLoop/ReadWriteProcess.pm#L340
> Fix race of SIG{CHLD} handler setup

- lib/Mojo/IOLoop/ReadWriteProcess.pm
- t/01_run.t
If `args` is given as scalar and the content is a false value, it was never given to the process as arguments.
> Fix `args` processing

- lib/Mojo/IOLoop/ReadWriteProcess.pm
- lib/Mojo/IOLoop/ReadWriteProcess/Session.pm
- t/01_run.t
This is a second option to fix this issue, see https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/pull/21. 
I would like to discuss what way fit's more.
The disadvantage of this process is, that we change the SIGMASK and the child will inherit it. 
But we only care of SIG_CHLD and this is reset in `fork()` path anyway.
> Fix race on `open3/fork` and `session->register($pid)` call -- second attempt

- t/04_queues.t
In the consume method, we use a `sleep .5`, which is equal to `sleep 0`
if we miss Time::HiRes.
I think it wasn't the intention, so including Time::HiRes might help?!
see: https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/blob/master/lib/Mojo/IOLoop/ReadWriteProcess/Queue.pm#L30
> Queue: add missing Time::HiRes

- Build.PL
- Changes
- META.json
- README.md
- lib/Mojo/IOLoop/ReadWriteProcess.pm
- minil.toml
Changelog diff is:
diff --git a/Changes b/Changes
index 3650797..b4e138f 100644
--- a/Changes
+++ b/Changes
@@ -3,6 +3,12 @@ Revision history for Perl extension Mojo-IOLoop-ReadWriteProcess
{{$NEXT}}
+0.32 2021-12-09T18:03:02Z
+ - Project moved to https://github.com/openSUSE/Mojo-IOLoop-ReadWriteProcess
+ - Introduce emit_from_sigchld()
+ - CI moved to GitHub Actions 
+
+
0.31 2021-12-01T15:51:06Z
- Fix bad release to cpan
- Enable GitHub Actions for the project
> Checking in changes prior to tagging of version 0.32.

- t/01_run.t
- t/data/sigchld_handler.pl
- t/data/simple_rwp.pl
During discussion of https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/issues/29
we realized that a tests like this need to be successful.
The reason for it is, if we use `session::protect()` when doing the
`fork()` or `open3()` then the sigmask of the child still has SIGCHLD
blocked.
> Add test for SIG_CHLD handler in spawned process

- t/01_run.t
- t/data/sigchld_handler.pl
- t/data/term_trap.sh
We encountered flaky 01_run.t tests with the error looks like:
```
```
It occurs in one out of ~300 runs. This fix assume, that we actually
send the SIGTERM before the executed script `term_trap.sh` has setup
it's traphandler to ignore such signal.
The fix just listen on STDOUT of the script to get informed, once the
sighandlers are setted and then continue.
A sleep would be ok as well, but it's harder to judge how long is a good
sleep :).
> Fix sporadic 01_run.t failure -- "process is still running"

- lib/Mojo/IOLoop/ReadWriteProcess/Session.pm
In Debian we are currently applying the following patch to
Mojo-IOLoop-ReadWriteProcess.
We thought you might be interested in it too.
Description: remove hard-coding of OABI syscall entry point
Package fails autopkgtests on armhf in Ubuntu because the kernel doesn't
expose the OABI syscall personality, and this code pointlessly hardcodes
a syscall number for the platform instead of using the system definition.
Bug-Debian: https://bugs.debian.org/1025824
Author: Steve Langasek <steve.langasek@ubuntu.com>
Reviewed-by: gregor herrmann <gregoa@debian.org>
Last-Update: 2022-12-11
The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libmojo-ioloop-readwriteprocess-perl/raw/master/debian/patches/wrong-arm-syscall-use.patch
Thanks for considering, …
> remove hard-coding of OABI syscall entry point

- t/01_run.t
- t/data/simple_rwp.pl
Tests will be skipped if the binary is not installed
> t: Add another check for /bin/true

- lib/Mojo/IOLoop/ReadWriteProcess.pm
One can set the `kill_whole_group` attribute to make the `stop` function of `ReadWriteProcess` stop the whole process group. This works in general but there are a few flaws this change addresses:
* Make `is_running` consider the whole process group as well. Otherwise, when the initial process is not running anymore `stop` returns early, even though there are still other processes left in the group.
* Avoid the use of `getpgrp` in the `stop` function. This function needs the PID to be still valid but this might not be the case when the initial process is not running anymore. The group ID is simply the PID of the initial process so we can just use that. (Assuming the the process group was created by invoking `setpgrp(0, 0)` in the code callback.)
I tested this by creating a simple script …
> Fix handling process groups when initial process is not running anymore

- lib/Mojo/IOLoop/ReadWriteProcess.pm
This fixes a bug introduced in ba7bb38 leading to `isotovideo can not be started` in openQA.
We must not *only* check the process group because it might not have been created. (The `is_running` function might be called immediately after `start` when `setpgrp(0, 0)` hasn't been executed yet.)
I tested this by putting `sleep 5` before `setpgrp(0, 0)`. Without this change openQA runs into `isotovideo can not be started` and with this change it works. I also tested whether cleanup of the whole process gorup still works.
Related ticket: https://progress.opensuse.org/issues/170209
> Fix race condition in `is_running` when `kill_whole_group` is set

- t/01_run.t
Wait until all sub processes have been forked before stopping the main sub process. This may help to avoid sporatic failure we sometimes see on OBS on ppc64le and aarch64 builds (probably because those machines tend to be slow).
Related ticket: https://progress.opensuse.org/issues/178183
---
This seems to help, see https://build.opensuse.org/package/show/home:mkittler:branches:devel:languages:perl/perl-Mojo-IOLoop-ReadWriteProcess. Of course this doesn't mean that much because the issue isn't always reproducible.
That will require `pgrep` to be installed in the test environment. The env for CI checks is currently broken anyway, though.
> Fix sporadic failures in `t/01_run.t`

- t/01_run.t
This will hopefully fix test failures like:
```
[  420s]     #   Failed test 'Process now is not running'
[  420s]     #   at t/01_run.t line 110.
[  420s]     #          got: '1'
[  420s]     #     expected: '0'
[  421s]     # Looks like you failed 1 test of 7.
[  421s]
[  421s] #   Failed test 'process is_running()'
[  421s] #   at t/01_run.t line 129.
[  427s] TEST error print
```
Related ticket: https://progress.opensuse.org/issues/178183
> Fix more instances where `t/01_run.t` might fail

- t/12_mocked_container.t
define return true even if the variable is empty, with this change the attempt continue to run unless the process_list contain some pid
related: https://progress.opensuse.org/issues/178186
> Update condition for process list definitions in 12_mocked_container

- .proverc
- t/01_run.t
$^X contains the path to perl the test was started with
Issue: https://progress.opensuse.org/issues/176148
> t: Use $^X for executing perl

- .github/workflows/ci-tests.yaml
* CI: Bump to codecov-action@v5
* CI: Use codecov token to prevent rate limit
* CI: Bump to codecov-action@v4
* CI: Fix indendation in version matrix
* CI: Simply use version 'latest' for codecov upload
* CI: Remove trailing space in title
* CI: Simplify 'on' definition
* CI: Add recent and current Perl versions
* CI: Use current version of checkout@v4
https://progress.opensuse.org/issues/176148
> CI: Update+fix+simplify

- Changes
- META.json
- lib/Mojo/IOLoop/ReadWriteProcess.pm
Use semver.org compatible version format and jump to 1.0.0 to avoid any
version computing ambiguities.
As per
https://github.com/semver/semver.org/issues/1 and
https://semver.org/#is-v123-a-semantic-version the version number itself
does not include a "v"-prefix itself however the prefix can be included
in denoting a version string.
References:
* https://semver.org/
* https://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html
* https://github.com/perlpunk/perl5-module-meta
* https://github.com/semver/semver.org/issues/1
> Prepare release of 1.0.0

- Build.PL
- Changes
- META.json
- README.md
- cpanfile
- lib/Mojo/IOLoop/ReadWriteProcess.pm
- minil.toml
* Prepare release of 1.1.0
* README: Update POD using minilla
* Try to prevent warnings about Formatter
* Update Build.PL and META.json with minilla 3.1.25
* Remove obsolete dependency on TAP::Formatter::Color
> Fix minil build + version 1.1.0

- .github/workflows/ci-tests.yaml
* And run with coverage only when also uploading the report
Before we collected also branch and condition coverage, which resulted
in a codecov.json file with items like "1/2" instead of just 1 or null.
> ci: Collect statement coverage only

- t/01_run.t
Otherwise the test might fail, and sometimes we don't even see an error message with the reason, like observed in OBS or probably here on cpantesters:
http://www.cpantesters.org/cpan/report/47446f5e-103b-11f0-98b0-b3c3213a625c http://www.cpantesters.org/cpan/report/57cba9ba-1017-11f0-98b0-b3c3213a625c
> t: Skip if pgrep is not installed
